# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.

fabric_name: {{ cookiecutter.general.fabric_name }}

underlay_routing_protocol: BGP

# Enable vlan aware bundles
vxlan_vlan_aware_bundles: {{ cookiecutter.general.vxlan_vlan_aware_bundles }}

# bgp peer groups passwords
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: {{ cookiecutter.general.bgp_peering_password }}
  EVPN_OVERLAY_PEERS:
    password: {{ cookiecutter.general.bgp_peering_password }}
  MLAG_IPv4_UNDERLAY_PEER:
    password: {{ cookiecutter.general.bgp_peering_password }}

# Spine Switches
spine:
  defaults:
    # IP address range for /32 EVPN loopbacks on spines
    # Assign range larger then total spines
    loopback_ipv4_pool: {{ cookiecutter.general.spine_loopback_ipv4_pool }}
  nodes:
{%- for spine in cookiecutter.fabric.spine_list %}
    {{ spine.hostname }}:
      id: {{ spine.id }}
      mgmt_ip: {{ spine.management_ip }}
      platform: {{ spine.platform }}
      bgp_as: {{ cookiecutter.general.spine_bgp_asn }}
{%-     if spine.mac_address is defined %}
      mac_address: '{{ spine.mac_address }}'
{%-     endif %}
{%- endfor %}

# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

l3leaf:
  defaults:
    # IP address range for /32 EVPN loopbacks on leafs
    # assign range larger then total leafs
    loopback_ipv4_pool: {{ cookiecutter.general.leaf_loopback_ipv4_pool }}
    vtep_loopback_ipv4_pool: {{ cookiecutter.general.l3leaf_vtep_loopback_ipv4_pool }}
    # adress pool for p2p underlay /31 links between l3leafs and spines
    # assign range larger then total [Spines * total potential leafs * 2]
    uplink_ipv4_pool: {{ cookiecutter.general.l3leaf_underlay_uplink_ipv4_pool }}
    # address pool for MLAG peering
    mlag_peer_ipv4_pool: {{ cookiecutter.general.mlag_peer_ipv4_pool }}
    # address pool for L3 peering over MLAG peer-link
    mlag_peer_l3_ipv4_pool: {{ cookiecutter.general.mlag_peer_l3_ipv4_pool }}
    # virtual router mac for VNIs assigned to Leaf switches
    # format: xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: {{ cookiecutter.general.virtual_router_mac_address }}
    spanning_tree_priority: {{ cookiecutter.general.l3leaf_stp_priority }}
    spanning_tree_mode: {{ cookiecutter.general.l3leaf_stp_mode }}
  node_groups:
{%- for pod in cookiecutter.fabric.pod_list %}
    {{ pod.name }}:
      bgp_as: {{ pod.asn }}
      nodes:
{%-     for leaf in pod.leafs %}
        {{ leaf.hostname }}:
          id: {{ leaf.id }}
          mgmt_ip: {{ leaf.management_ip }}
          platform: {{ leaf.platform }}
          uplink_switches: {{ leaf.spines }}
          uplink_interfaces: {{ leaf.uplink_to_spine_interfaces }}
          uplink_switch_interfaces: {{ leaf.spine_interfaces }}
{%-         if leaf.mac_address is defined %}
          mac_address: '{{ leaf.mac_address }}'
{%-         endif %}
          mlag_interfaces: {{ leaf.mlag_interfaces }}
{%-     endfor %}
{%- endfor %}

p2p_uplinks_mtu: {{ cookiecutter.general.underlay_p2p_link_mtu }}
