---
port_profiles:
{%- for server_port_profile in cookiecutter.csv.server_port_profiles %}
  {{ server_port_profile.profile_name }}:
    {% if server_port_profile.switchport_mode %}mode: {{ server_port_profile.switchport_mode }}{% endif %}
    {% if server_port_profile.vlan_string %}vlans: {{ server_port_profile.vlan_string }}{% endif %}
{%- endfor %}

servers:
{%- for server in cookiecutter.services.servers %}
  {{ server.name }}:
    rack: {{ server.rack }}
    # NOTE: the server template does not support multiple adapters
    # just create a server with a different name prefix/postfix instead
    adapters:
    - type: nic
      endpoint_ports: {{ server.endpoint_ports }}
      switch_ports: {{ server.switch_ports }}
      switches: {{ server.switches }}
      {% if server.profile is defined %}profile: {{ server.profile }}{% endif %}
{%-     if server.port_channel is defined %}
      port_channel:
        description: {{ server.description }}
        mode: {{ server.port_channel.mode }}
        state: present
{%-     endif %}
{%- endfor %}
