---
- name: "Run Fabric states validation"
  hosts: {{cookiecutter.fabric_name}}
  connection: httpapi
  gather_facts: false
  collections:
    - arista.avd
  tasks:

    - name: deploy configuration to device
      import_role:
         name: arista.avd.eos_validate_state