---
port_profiles:
  TENANT_A:
    mode: access
    vlans: 110

servers:
  host2:
    rack: pod2
    # NOTE: the server template does not support multiple adapters
    # just create a server with a different name prefix/postfix instead
    adapters:
    - type: nic
      endpoint_ports: ['leaf3_to_host2', 'leaf3_to_host2']
      switch_ports: ['Ethernet5', 'Ethernet5']
      switches: ['leaf3', 'leaf4']
      profile: TENANT_A
      port_channel:
        description: leaf3_to_host2
        mode: active
        state: present
  host1:
    rack: pod1
    # NOTE: the server template does not support multiple adapters
    # just create a server with a different name prefix/postfix instead
    adapters:
    - type: nic
      endpoint_ports: ['leaf1_to_host1', 'leaf1_to_host1']
      switch_ports: ['Ethernet5', 'Ethernet5']
      switches: ['leaf1', 'leaf2']
      profile: TENANT_A
      port_channel:
        description: leaf1_to_host1
        mode: active
        state: present
