tenants:
  Tenant_A:
    mac_vrf_vni_base: 10000
    vrfs:
      Tenant_A_OP_Zone:
        vrf_vni: 10
        vtep_diagnostic:
          loopback: 100
          loopback_ip_range: 10.255.1.0/24
        svis:
          110:
            name: Tenant_A_OP_Zone_1
            tags: ['opzone', 'another_tag']
            enabled: true
            ip_address_virtual: 10.1.10.1/24
            
            
    l2vlans:
      160:
        name: Tenant_A_VMOTION
        tags: ['vmotion']